import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import localFont from "next/font/local";
import Footer from "@/components/layout/footer/Footer";
const helvetica = localFont({
  src: "../../public/fonts/alfont_com_AlFont_com_helveticaneueltarabicroman1.ttf",
  variable: "--font-helvetica",
});
export const metadata: Metadata = {
  title: "Mayadeen",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-main ${helvetica.variable} overflow-x-hidden`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
